// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// Default [FirebaseOptions] for use with your Firebase apps.
//
// Example:
// ```dart
// import 'firebase_options.dart';
// // ...
// await Firebase.initializeApp(
//   options: DefaultFirebaseOptions.currentPlatform,
// );
// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH_NvF2Lr5rgpC4Bi33eiwn2EdOk0En4k',
    appId: '1:266056580802:web:709e2eb5210e6df9e9855b',
    messagingSenderId: '266056580802',
    projectId: 'timeless-6cdf9',
    authDomain: 'timeless-6cdf9.firebaseapp.com',
    storageBucket: 'timeless-6cdf9.firebasestorage.app',
    measurementId: 'G-NSE4SCGRMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzMiRl45QQ7xsqNeb6dn5Kra8z-T1c2pE',
    appId: '1:266056580802:android:6e7f5d338f7d4e92e9855b',
    messagingSenderId: '266056580802',
    projectId: 'timeless-6cdf9',
    storageBucket: 'timeless-6cdf9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2HZ9jTvLpCJaPF6NKWKER7z54-IxS3pE',
    appId: '1:266056580802:ios:fc7c987d1d066e58e9855b',
    messagingSenderId: '266056580802',
    projectId: 'timeless-6cdf9',
    storageBucket: 'timeless-6cdf9.firebasestorage.app',
    androidClientId:
        '266056580802-s1n7ha6hvuqoiqsqqri67pprmpg10p4a.apps.googleusercontent.com',
    iosClientId:
        '266056580802-otnm8oja92k0u0fu4mb09l6hj75shbol.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeless',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2HZ9jTvLpCJaPF6NKWKER7z54-IxS3pE',
    appId: '1:266056580802:ios:fc7c987d1d066e58e9855b',
    messagingSenderId: '266056580802',
    projectId: 'timeless-6cdf9',
    storageBucket: 'timeless-6cdf9.firebasestorage.app',
    androidClientId:
        '266056580802-s1n7ha6hvuqoiqsqqri67pprmpg10p4a.apps.googleusercontent.com',
    iosClientId:
        '266056580802-otnm8oja92k0u0fu4mb09l6hj75shbol.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeless',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCH_NvF2Lr5rgpC4Bi33eiwn2EdOk0En4k',
    appId: '1:266056580802:web:d7c84116db04def6e9855b',
    messagingSenderId: '266056580802',
    projectId: 'timeless-6cdf9',
    authDomain: 'timeless-6cdf9.firebaseapp.com',
    storageBucket: 'timeless-6cdf9.firebasestorage.app',
    measurementId: 'G-029XWLSHPF',
  );
}
